workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: development
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run Android build
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
