
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: development
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Run Android build
        script: cd android
                ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
